source "https://rubygems.org"

gem "sinatra"
gem "sqlite3"
gem "activerecord"
gem "sinatra-activerecord"
gem "rake"
gem "data_mapper"
gem "haml"
gem "dm-sqlite-adapter"

group :development do
  gem "shotgun"
  gem "tux"
end